In [8]:
import random

salary_list = [random.randint(50000, 100000) for _ in range(1_000_000)]

In [10]:
%%timeit


import statistics
statistics.mean(salary_list)

371 ms ± 111 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
import numpy as np

In [12]:
%%timeit
np.mean(salary_list)

52.6 ms ± 5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
my_array = np.array([1, 2, 3, 4])

In [17]:
my_array.mean()

2.5

In [20]:
import random

salary = [random.randint(100000, 150000) for num in range(10)]

In [21]:
salary_array = np.array(salary)
salary_array

array([133120, 114769, 149254, 132028, 134322, 143500, 111218, 101957,
       120266, 112772])

In [22]:
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

1253206

In [23]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [24]:
salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

In [25]:
# Replace values using np.where
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

array([133120, 120000, 149254, 132028, 134322, 143500, 120000, 120000,
       120266, 120000])

In [26]:
# Generate numbers based on normal distribution
noise = np.random.normal(0, 5000, salary_array.size)
# Add these numbers to the salary_array
salary_array_with_noise = salary_array + noise
salary_array_with_noise

array([131674.83197974, 124280.86147522, 159552.78541809, 127659.59701284,
       135609.26106264, 147716.12055952, 118785.51258729, 124326.21333845,
       126528.05374099, 116098.6670011 ])